[project]
name = "ml-ops-hw03"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.124.4",
    "loguru>=0.7.3",
    "prometheus-client>=0.23.1",
    "pydantic-settings>=2.12.0",
    "uvicorn>=0.38.0",
]
